---
- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
    application: finalprojectdevelopment
  tasks:
    - name: create instances
      include_role: 
        name: create_instance
